on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write

name: lerna
jobs:
  changeFinder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Testing
        run: npx lerna changed -a
