name: NPM Package

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate commits
        uses: webiny/action-conventional-commits@v1.1.0

  test-build-publish:
    needs: [validate-commits]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@bepower'

      - name: Install dependencies
        run: npm ci

      - name: Testing
        run: npm test --workspaces --if-present

      - name: Building typescript in packages
        run: npm run build --workspaces --if-present

      - name: Linting
        run: npm run check

      - name: Publish
        run: 'npx auto shipit --message "ci: :memo: Update CHANGELOG.md [skip ci]"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
