name: Auto compile README.md
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Regenerate Readme
        run: node scripts/regenerate-readme.js

      - name: check for changes
        run: |
          if git diff --exit-code; then
            echo "::set-env name=changes_exist::true"
          else
            echo "::set-env name=changes_exist::false"
          fi

      - name: Configure git, commit and push
        if: ${{ env.changes_exist == 'true' }}
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          git add .
          git commit -m "chore(docs): :memo: Auto generate readme"
          git push
