on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write

name: release-please
jobs:
  changeFinder:
    runs-on: ubuntu-latest
    outputs:
      nodePaths: ${{ steps.interrogate.outputs.result }}
    steps:
      - uses: actions/checkout@v4

      - id: interrogate
        uses: actions/github-script@v7
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            retries: 5
            script: |
              const {execSync} = require('child_process');
              const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
              const latestRelease = await github.rest.repos.getLatestRelease({
                owner,
                repo
              });
              console.log(`latest release: ${JSON.stringify(latestRelease.data)}`);
              execSync('git pull --tags');
              execSync(`git reset --hard ${latestRelease.data.tag_name}`);
              const status = execSync(`git diff --name-only origin/main`, { encoding: 'utf-8'});
              console.log(status);
              const changes = status.split('\n');
              let nodePaths = new Set();
              for (const change of changes) {
                if (change.startsWith('packages/')) {
                    const library = change.split('/')[1];
                    nodePaths.add(library);
                };
              }
              nodePaths = Array.from(nodePaths);
              return nodePaths;
              // console.log(`::set-output name=nodePaths::${JSON.stringify(nodePaths)}`);

  release-please-release:
    runs-on: ubuntu-latest
    needs: changeFinder
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.changeFinder.outputs.nodePaths) }}
    steps:
      - name: Get result
        run: echo "${{ matrix.package }}"
